/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#c9e6ff",
        "on-tertiary-fixed-variant": "#434750",
        "secondary-fixed-dim": "#c4c6ce",
        "surface-tint": "#89ceff",
        "tertiary": "#c3c6d2",
        "surface-bright": "#37393e",
        "inverse-surface": "#e2e2e8",
        "surface-container-lowest": "#0c0e12",
        "secondary-fixed": "#e1e2ea",
        "on-surface": "#e2e2e8",
        "on-tertiary": "#2c303a",
        "tertiary-container": "#989ba6",
        "on-primary-fixed": "#001e2f",
        "background": "#0F1115",
        "on-primary-container": "#003751",
        "error": "#ffb4ab",
        "secondary": "#c4c6ce",
        "primary": "#89ceff",
        "on-background": "#e2e2e8",
        "surface-variant": "#333539",
        "tertiary-fixed-dim": "#c3c6d2",
        "tertiary-fixed": "#dfe2ee",
        "outline-variant": "#3e4850",
        "surface": "#111317",
        "on-tertiary-fixed": "#181c24",
        "inverse-on-surface": "#2f3035",
        "on-secondary-container": "#b6b8c0",
        "surface-dim": "#111317",
        "surface-container-highest": "#333539",
        "secondary-container": "#464950",
        "outline": "#88929b",
        "on-tertiary-container": "#2f333c",
        "on-secondary-fixed-variant": "#44474d",
        "on-surface-variant": "#bec8d2",
        "on-primary": "#00344d",
        "surface-container-high": "#282a2e",
        "primary-container": "#0ea5e9",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-secondary": "#2d3037",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004c6e",
        "surface-container-low": "#1a1c20",
        "on-secondary-fixed": "#191c22",
        "inverse-primary": "#006591",
        "surface-container": "#1e2024",
        "primary-fixed-dim": "#89ceff"
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-padding": "40px",
        "stack-sm": "8px",
        "grid-gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
